# Generated by Django 4.2.10 on 2025-04-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeactivity',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('MF', 'Mutual Fund'), ('CRYPTO', 'Cryptocurrency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeactivity',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20),
        ),
    ]
